services:
  - type: web
    name: chickentinders
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: IS_PRODUCTION
        value: true
      - key: VITE_API_URL
        value: /api
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: COOKIE_SECRET
        sync: false
