services:
  - type: web
    name: chickentinders
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: IS_PRODUCTION
        value: true
      - key: VITE_API_URL
        value: ""
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: CHECK_FOR_THIS_STRING
        value: "true"
      - key: FRONTEND_URL
        sync: false
      - key: YELP_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VITE_VAPID_PUBLIC_KEY
        sync: false
